# Generated by Django 3.2.11 on 2022-06-20 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
