# Generated by Django 3.2.11 on 2022-06-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20220620_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='todo.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', related_query_name='todo_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
