# Generated by Django 3.2.11 on 2022-03-28 21:41

from django.db import migrations, models


def populate_name_long(apps, schema_editor):
    Cinema = apps.get_model('critique', 'Cinema')
    for cinema in Cinema.objects.all():
        cinema.name_long = cinema.name
        cinema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='location',
            field=models.CharField(max_length=100, default="Paris"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_long',
            field=models.CharField(max_length=100, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_short',
            field=models.CharField(blank=True, null=True, max_length=100, unique=True),
        ),
        migrations.RunPython(populate_name_long),
        migrations.AlterField(
            model_name='cinema',
            name='name_long',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
