# Generated by Django 3.2.11 on 2022-04-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0004_auto_20220402_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='cinema',
        ),
    ]
