# Generated by Django 3.2.11 on 2022-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0005_remove_seance_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='cinema_pk',
            new_name='cinema',
        ),
    ]
