# Generated by Django 3.2.11 on 2022-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0006_rename_cinema_pk_seance_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date_day_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
