# Generated by Django 3.2.11 on 2022-05-16 21:45

from django.db import migrations, models
from django.template.defaultfilters import slugify


def add_slug(apps, schema_editor):
    OeuvreTag = apps.get_model('critique', 'OeuvreTag')
    for tag in OeuvreTag.objects.all():
        tag.slug = slugify(tag.name)
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0007_seance_date_day_unknown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='OeuvreTag',
        ),
        migrations.AddField(
            model_name='oeuvretag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_slug),
        migrations.AlterField(
            model_name='oeuvretag',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='oeuvretag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
