# Generated by Django 3.2.11 on 2022-05-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0008_overhaul_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvretag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
