# Generated by Django 3.2.11 on 2022-05-21 17:28

from django.db import migrations, models
import django.db.models.deletion


def add_spans_to_seances(apps, schema_editor):
    Seance = apps.get_model('critique', 'Seance')
    OeuvreSpan = apps.get_model('critique', 'OeuvreSpan')
    for seance in Seance.objects.all():
        span = OeuvreSpan(
            oeuvre=seance.film,
            date_start=seance.date,
            dsdu=seance.date_day_unknown,
            dsmu=seance.date_month_unknown,
        )
        span.save()
        seance.oeuvre_span = span
        seance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0009_fix_tag_slugfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeuvreSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('dsdu', models.BooleanField(default=False)),
                ('dsmu', models.BooleanField(default=False)),
                ('date_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('dedu', models.BooleanField(blank=True, default=False)),
                ('demu', models.BooleanField(blank=True, default=False)),
                ('oeuvre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spans', related_query_name='span', to='critique.oeuvre')),
            ],
        ),
        migrations.AddField(
            model_name='seance',
            name='oeuvre_span',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='critique.oeuvrespan', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_spans_to_seances),
        migrations.AlterField(
            model_name='seance',
            name='oeuvre_span',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='critique.oeuvrespan'),
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date_day_unknown',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date_month_unknown',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='film',
        ),
    ]
