# Generated by Django 3.2.11 on 2022-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0010_auto_20220521_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvrespan',
            name='ongoing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
