# Generated by Django 3.2.11 on 2022-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0011_oeuvrespan_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvrespan',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
