# Generated by Django 3.2.11 on 2022-05-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0013_auto_20220528_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='info',
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='artists',
            field=models.ManyToManyField(related_name='oeuvres', related_query_name='oeuvre', to='critique.Artiste'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='mtype',
            field=models.CharField(choices=[('film', 'Film'), ('serie', 'Série'), ('album', 'Album'), ('jeu', 'Jeu'), ('livre', 'Livre'), ('bd', 'BD')], max_length=5),
        ),
        migrations.DeleteModel(
            name='OeuvreInfo',
        ),
        migrations.DeleteModel(
            name='Titres',
        ),
    ]
