# Generated by Django 3.2.11 on 2022-06-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0014_auto_20220528_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='date_day_unknown',
            new_name='date_du',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='date_month_unknown',
            new_name='date_mu',
        ),
        migrations.RenameField(
            model_name='oeuvrespan',
            old_name='dedu',
            new_name='date_end_du',
        ),
        migrations.RenameField(
            model_name='oeuvrespan',
            old_name='demu',
            new_name='date_end_mu',
        ),
        migrations.RenameField(
            model_name='oeuvrespan',
            old_name='dsdu',
            new_name='date_start_du',
        ),
        migrations.RenameField(
            model_name='oeuvrespan',
            old_name='dsmu',
            new_name='date_start_mu',
        ),
    ]
