# Generated by Django 3.2.11 on 2022-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0015_auto_20220601_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='image',
            field=models.ImageField(blank=True, upload_to='oeuvre_imgs'),
        ),
    ]
