# Generated by Django 3.2.11 on 2022-06-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0016_oeuvre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='image',
            field=models.ImageField(blank=True, upload_to='oeuvres_img'),
        ),
    ]
