# Generated by Django 4.2.11 on 2024-05-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0017_auto_20220603_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiste',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='oeuvretag',
            options={'ordering': ['name']},
        ),
    ]
