# Generated by Django 4.2.11 on 2025-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("critique", "0018_alter_artiste_options_alter_cinema_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="tgdb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="tgdb_altslug",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
