# Generated by Django 4.2.11 on 2025-07-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("critique", "0019_commentaire_tgdb_commentaire_tgdb_altslug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentaire",
            old_name="tgdb_altslug",
            new_name="tgdb_slug",
        ),
    ]
