# Generated by Django 4.2.11 on 2025-09-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0020_rename_tgdb_altslug_commentaire_tgdb_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topjeux',
            name='jeux',
        ),
        migrations.DeleteModel(
            name='TopFilms',
        ),
        migrations.DeleteModel(
            name='TopJeux',
        ),
    ]
