# Generated by Django 4.2.11 on 2025-10-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("critique", "0021_remove_topjeux_jeux_delete_topfilms_delete_topjeux"),
    ]

    operations = [
        migrations.CreateModel(
            name="TierList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.SmallIntegerField()),
                (
                    "oeuvres",
                    models.ManyToManyField(
                        related_name="tiers",
                        related_query_name="tier",
                        to="critique.oeuvre",
                    ),
                ),
                (
                    "tier_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        related_query_name="tier",
                        to="critique.tierlist",
                    ),
                ),
            ],
            options={
                "ordering": ["tier_list__created_at", "position"],
            },
        ),
    ]
