# Generated by Django 4.2.11 on 2025-10-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("critique", "0022_tierlist_tier"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tier",
            constraint=models.UniqueConstraint(
                fields=("tier_list", "position"), name="unique_position"
            ),
        ),
    ]
